# Generated by Django 4.2.5 on 2023-10-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=20)),
                ("bank_name", models.CharField(max_length=100)),
                ("branch", models.CharField(max_length=100)),
                ("swift_code", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "amount_or_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "discount_type",
                    models.IntegerField(choices=[(1, "Amount"), (2, "Percentage")]),
                ),
                ("applicable_start_date", models.DateField()),
                ("applicable_end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expense_date", models.DateField()),
                ("description", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="FeeStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "frequency",
                    models.IntegerField(
                        choices=[
                            (1, "Daily"),
                            (2, "Weekly"),
                            (3, "Monthly"),
                            (4, "Quarterly"),
                            (5, "Annually"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Unpaid"),
                            (2, "Partially Paid"),
                            (3, "Fully Paid"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LateFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "late_fee_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("effective_start_date", models.DateField()),
                ("effective_end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField()),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_method", models.CharField(max_length=20)),
                ("transaction_reference", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "amount_received",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("refund_date", models.DateField()),
                (
                    "amount_refunded",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("reason", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TransactionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Invoice Created"),
                            (2, "Payment Received"),
                            (3, "Refund Issued"),
                        ]
                    ),
                ),
                ("details", models.TextField()),
            ],
        ),
    ]
