# Generated by Django 4.2.5 on 2023-10-06 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("school", "0001_initial"),
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.staff"
            ),
        ),
        migrations.AddField(
            model_name="staffattendance",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="users.staff"
            ),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academics.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.staff",
            ),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.school",
            ),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="students",
            field=models.ManyToManyField(
                related_name="enrolled_classes", to="users.student"
            ),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="subjects",
            field=models.ManyToManyField(
                related_name="classes_taught", to="academics.subject"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.school",
            ),
        ),
        migrations.AddField(
            model_name="attendancereport",
            name="attendance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.timetable"
            ),
        ),
        migrations.AddField(
            model_name="attendancereport",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.school",
            ),
        ),
        migrations.AddField(
            model_name="attendancereport",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="users.student"
            ),
        ),
        migrations.AddField(
            model_name="academicyear",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.school",
            ),
        ),
    ]
