# Generated by Django 4.2.5 on 2023-10-06 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("school", "0001_initial"),
        ("housing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentaccommodation",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.student"
            ),
        ),
        migrations.AddField(
            model_name="roomallocation",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="housing.room"
            ),
        ),
        migrations.AddField(
            model_name="roomallocation",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.student"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="hostel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="housing.hostel"
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="housing.room"
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.student"
            ),
        ),
        migrations.AddField(
            model_name="hostel",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="school.school"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentaccommodation",
            unique_together={("student", "room")},
        ),
        migrations.AlterUniqueTogether(
            name="hostel",
            unique_together={("school", "name")},
        ),
    ]
